# Same as Black.
line-length = 120

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    #  Not for the dojo specific stuff
    "dojo/db_migrations"
]

[lint]
select = [
   "AIR",
   "FAST",
   "YTT",
   "ASYNC",
   "S",
   "FBT",
   "B",
   "A",
   "COM",
   "C4",
   "DTZ",
   "T10",
   "DJ",
   "EM",
   "EXE",
   "FIX",
   "FA",
   "INT",
   "ISC",
   "ICN",
   "LOG",
   "G",
   "INP",
   "PIE",
   "T20",
   "PYI",
   "PT",
   "Q",
   "RSE",
   "RET",
   "SIM",
   "SLOT",
   "TID",
   "invalid-todo-tag", "missing-todo-description", "missing-space-after-todo-colon",
   "TC",
   "unused-class-method-argument", "unused-static-method-argument", "unused-lambda-argument",
   "PTH",
   "FLY",
   "I",
   "C90",
   "NPY",
   "PD",
   "N",
   "PERF1", "PERF2", "manual-dict-comprehension",
   "E",
   "W",
   "docstring-extraneous-returns", "docstring-extraneous-yields", "docstring-extraneous-exception",
   "D2", "D3", "signature-in-docstring", "first-word-uncapitalized", "non-capitalized-section-name", "missing-new-line-after-section-name", "missing-dashed-underline-after-section", "missing-section-underline-after-name", "mismatched-section-underline-length", "no-blank-line-after-section", "no-blank-line-before-section", "blank-lines-between-header-and-content", "missing-blank-line-after-last-section", "empty-docstring-section", "missing-section-name-colon",
   "F",
   "PGH",
   "PLC0", "PLC1", "PLC24", "PLC28", "PLC3",
   "PLE",
   "PLR01", "PLR02", "PLR04", "too-many-statements", "useless-return", "redefined-argument-from-local", "repeated-equality-comparison", "boolean-chained-comparison", "PLR172", "PLR173", "empty-comment", "PLR5", "non-augmented-assignment", "literal-membership", 
   "PLW",
   "UP",
   "FURB",
   "RUF",
   "TRY",
]
ignore = [
    "line-too-long",
    "bare-except",
    "boolean-default-value-positional-argument",
    "unnecessary-collection-call",
    "implicit-namespace-package",
    "implicit-namespace-package",
    "invalid-function-name",
    "invalid-argument-name",
    "non-lowercase-variable-in-function",
    "if-else-block-instead-of-if-exp",
    "implicit-return",
    "unnecessary-multiline-docstring",
    "builtin-argument-shadowing",
    "mutable-argument-default",
    "print",
    "ambiguous-unicode-character-docstring",
    "mutable-class-default",
    "unnecessary-iterable-allocation-for-first-element",
    "missing-blank-line-after-summary",
    "line-contains-todo",
    "blank-line-before-class",  # `one-blank-line-before-class` (D203) and `no-blank-line-before-class` (D211) are incompatible.
    "multi-line-summary-first-line",  # `multi-line-summary-first-line` (D212) and `multi-line-summary-second-line` (D213) are incompatible.
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
preview = true

[lint.flake8-boolean-trap]
extend-allowed-calls = ["dojo.utils.get_system_setting"]

[lint.pylint]
max-statements = 234

[lint.mccabe]
max-complexity = 70  # value is far from perfect (recommended default is 10). But we will try to decrease it over the time.