# Same as Black.
line-length = 120

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    #  Not for the dojo specific stuff
    "dojo/db_migrations"
]

[lint]
select = [
   "AIR",
   "FAST",
   "YTT",
   "ASYNC",
   "S",
   "FBT",
   "B",
   "A",
   "COM",
   "C4",
   "DTZ",
   "T10",
   "DJ",
   "EM",
   "EXE",
   "FIX",
   "FA",
   "INT",
   "ISC",
   "ICN",
   "LOG",
   "G",
   "INP",
   "PIE",
   "T20",
   "PYI",
   "PT",
   "Q",
   "RSE",
   "RET",
   "SIM",
   "SLOT",
   "TID",
   "TD001", "TD005", "TD007",
   "TC",
   "ARG003", "ARG004", "ARG005",
   "PTH",
   "FLY",
   "I",
   "C90",
   "NPY",
   "PD",
   "N",
   "PERF1", "PERF2", "PERF403",
   "E",
   "W",
   "DOC202", "DOC403", "DOC502",
   "D2", "D3", "D402", "D403", "D405", "D406", "D407", "D408", "D409", "D410", "D411", "D412", "D413", "D414", "D416",
   "F",
   "PGH",
   "PLC0", "PLC1", "PLC24", "PLC28", "PLC3",
   "PLE",
   "PLR01", "PLR02", "PLR04", "PLR0915", "PLR1711", "PLR1704", "PLR1714", "PLR1716", "PLR172", "PLR173", "PLR2044", "PLR5", "PLR6104", "PLR6201", 
   "PLW",
   "UP",
   "FURB",
   "RUF",
   "TRY",
]
ignore = [
    "E501",
    "E722",
    "FBT002",
    "C408",
    "INP001",
    "INP001",
    "N802",
    "N803",
    "N806",
    "SIM108",
    "RET503",
    "D200",
    "A002",
    "B006",
    "T201",
    "RUF002",
    "RUF012",
    "RUF015",
    "D205",
    "FIX002",
    "D211",  # `one-blank-line-before-class` (D203) and `no-blank-line-before-class` (D211) are incompatible.
    "D212",  # `multi-line-summary-first-line` (D212) and `multi-line-summary-second-line` (D213) are incompatible.
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
preview = true

[lint.flake8-boolean-trap]
extend-allowed-calls = ["dojo.utils.get_system_setting"]

[lint.pylint]
max-statements = 234

[lint.mccabe]
max-complexity = 70  # value is far from perfect (recommended default is 10). But we will try to decrease it over the time.